# Generated by Django 5.2.17 on 2026-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('audio', 'Audio'), ('wearables', 'Wearables'), ('home', 'Home'), ('office', 'Office'), ('kitchen', 'Kitchen'), ('fitness', 'Fitness'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
