# Generated by Django 5.2.17 on 2026-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptops', 'Laptops'), ('keyboards', 'Keyboards'), ('gaming', 'Gaming gear'), ('cpus', 'CPUs'), ('gpus', 'Graphics cards'), ('ram', 'Memory'), ('monitors', 'Monitors'), ('pcs', 'Gaming PCs'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
