# Generated by Django 5.2.18 on 2026-10-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_fx_rate_observed_at_order_fx_rate_source_and_more'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='recommendation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='recommendation.recommendationrun'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=24),
        ),
    ]
