# Generated by Django 5.2.18 on 2026-10-07 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_order_fx_rate_observed_at_order_fx_rate_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_sha256', models.CharField(db_index=True, max_length=64)),
                ('requested_categories', models.JSONField(blank=True, default=list)),
                ('budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('candidate_product_ids', models.JSONField(blank=True, default=list)),
                ('candidate_count', models.PositiveSmallIntegerField(default=0)),
                ('in_stock_count', models.PositiveSmallIntegerField(default=0)),
                ('search_mode', models.CharField(choices=[('keyword', 'Keyword fallback'), ('vector', 'Vector search'), ('category', 'Category match')], max_length=12)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('click', 'Product click'), ('purchase', 'Paid order')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_interaction', to='products.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recommendation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recommendation.recommendationrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='recommendationrun',
            index=models.Index(fields=['-created_at', 'search_mode'], name='recommendat_created_9f5abe_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationinteraction',
            index=models.Index(fields=['recommendation_run', 'kind', 'created_at'], name='recommendat_recomme_62641f_idx'),
        ),
    ]
