# Generated by Django 5.2.18 on 2026-10-07 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_orderitem_recommendation_run_alter_order_status'),
        ('recommendation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationrun',
            name='empty_reason',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='recommendationrun',
            name='empty_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendationrun',
            name='matched_product_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendationrun',
            name='within_budget_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationinteraction',
            name='kind',
            field=models.CharField(choices=[('click', 'Product click'), ('purchase', 'Paid order'), ('irrelevant', 'Marked as irrelevant')], max_length=12),
        ),
        migrations.AlterField(
            model_name='recommendationrun',
            name='in_stock_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='recommendationinteraction',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'irrelevant')), fields=('recommendation_run', 'product'), name='unique_irrelevant_feedback_per_product_run'),
        ),
    ]
