# Generated by Django 5.2.17 on 2026-09-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_payment_amount_alter_wallettransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='ip_location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
