# Generated by Django 5.2.18 on 2026-10-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_checkout_token_paymentwebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
