# Generated by Django 5.2.18 on 2026-10-07 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_checkout_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'source', 'observed_at'), name='unique_exchange_rate_source_observation'),
        ),
    ]
