# Generated by Django 5.2.17 on 2026-09-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='source',
            field=models.CharField(choices=[('api', 'API'), ('telegram', 'Telegram'), ('catalog', 'Product catalog')], max_length=12),
        ),
    ]
